/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/kU0LFmFQ3Eb
 */
import { Button } from "../components/ui/button"
import { Label } from "../components/ui/label"
import { Input } from "../components/ui/input"
import { Textarea } from "../components/ui/textarea"
import Link from "next/link"

function itemchecker() {
  return (
    (
       <><header className="px-4 lg:px-6 h-14 flex items-center">
        <Link className="flex items-center justify-center" href="#">
          <MountainIcon className="h-6 w-6" />
          <span className="sr-only">Acme Inc</span>
        </Link>
        <div>


          {/* <navbar className="text-sm font-medium hover:underline underline-offset-4" /> */}
        </div>

        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="/">
            Home
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="/itemChecker">
            Item Checker
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="/findRestaurant">
            Sustainable Restaurants
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="/trackTransport">
            Daily Transportation Tracker
          </Link>
        </nav>
      </header><div className="mx-auto max-w-3xl space-y-6">
          <div className="space-y-2 text-center">
            <h1 className="text-3xl font-bold">Scan or upload barcode</h1>
            <p className="text-gray-500 dark:text-gray-400">
              Scan the barcode on a product to view sustainability information
            </p>
          </div>
          <div className="flex justify-center">
            <Button>Scan Barcode</Button>
            <input accept="image/*" className="sr-only" id="upload" type="file" />
            <label
              className="cursor-pointer inline-block w-[200px] sm:w-[250px] [&:disabled]bg-gray-300 dark:[&:disabled]bg-gray-700 height-12 flex items-center justify-center rounded-lg text-sm transition-colors border border-gray-200 dark:border-gray-800 dark:disabled:[&:border-gray-700] disabled:opacity-70 disabled:cursor-not-allowed dark:border-gray-800"
              htmlFor="upload">
              Upload Image
            </label>
          </div>
          <div className="grid gap-4">
            <div className="grid gap-2">
              <Label className="text-sm" htmlFor="name">
                Product Name
              </Label>
              <Input id="name" value="Acme Prism T-Shirt" />
            </div>
            <div className="grid gap-2">
              <Label className="text-sm" htmlFor="brand">
                Brand
              </Label>
              <Input id="brand" value="Acme Apparel" />
            </div>
            <div className="grid gap-2">
              <Label className="text-sm" htmlFor="description">
                Description
              </Label>
              <Textarea id="description" />
            </div>
            <div className="grid gap-2">
              <Label className="text-sm" htmlFor="sustainability">
                Sustainability Rating
              </Label>
              <Input id="sustainability" value="80" />
            </div>
            <div className="grid gap-2">
              <Label className="text-sm" htmlFor="carbon">
                Carbon Efficiency
              </Label>
              <Input disabled id="carbon" placeholder="Calculate" />
              <Button>Calculate</Button>
            </div>
          </div>
        </div></>)
  );
}

function MountainIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>)
  );
}

export default itemchecker;
