/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/UBYnLRXJUos
 */
import { CardTitle, CardDescription, CardHeader, Card } from "@/components/ui/card"

export function recom() {
  return (
    (<section className="w-full py-12 md:py-24 lg:py-32">
      <div
        className="container grid items-center justify-center gap-4 px-4 text-center md:px-6 lg:gap-10">
        <div className="space-y-3">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
            How To Reduce Your Carbon Footprint
          </h2>
          <p
            className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
            Personalized recommendations for you.
          </p>
        </div>
        <div
          className="grid w-full grid-cols-1 items-stretch justify-center gap-4 md:grid-cols-3 md:gap-8">
          <div className="mx-auto flex w-full items-center justify-center p-6 sm:p-8">
            <Card className="h-full">
              <CardHeader>
                <CardTitle className="text-xl">Go Veg</CardTitle>
                <CardDescription>Try out a meatless meal 1x per week</CardDescription>
              </CardHeader>
            </Card>
          </div>
          <div className="mx-auto flex w-full items-center justify-center p-6 sm:p-8">
            <Card className="h-full">
              <CardHeader>
                <CardTitle className="text-xl">Two Wheels</CardTitle>
                <CardDescription>Bike or take public transit instead of a car 2x per week</CardDescription>
              </CardHeader>
            </Card>
          </div>
          <div className="mx-auto flex w-full items-center justify-center p-6 sm:p-8">
            <Card className="h-full">
              <CardHeader>
                <CardTitle className="text-xl">Quality Over Quantity</CardTitle>
                <CardDescription>Try to reduce your clothing consumption by 1 purchase per month</CardDescription>
              </CardHeader>
            </Card>
          </div>
        </div>
      </div>
    </section>)
  );
}
