/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Wg5DEbQVoid
 */
"use client"
import Link from "next/link"
import { Input } from "@/app/components/ui/input"
import { Button } from "@/app/components/ui/button"
import logo from './app/pages/download_img.jpeg';

const MainPage = () => {
  return (
    (<div className="flex flex-col min-h-[100dvh]">
      <div className="items-center">
      <main className="flex-1 items-center">
        <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48 items-center">
          <div
            className="container flex flex-col items-center gap-4 px-4 md:px-6 text-center">
            <div className="space-y-2 text-center">
              <h1
                className="text-3xl font-bold tracking-tighter sm:text-5xl md:text-6xl/none">
                Carbon Footprint Tracker
              </h1>
              <p
                className="max-w-[800px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Track your impact on the planet. Understand. Reduce. Improve.
              </p>
            </div>
          </div>
        </section>
        <section
          className="w-full py-12 md:py-24 lg:py-32 border-t border-gray-200 dark:border-gray-800">
          <div className="container flex flex-col gap-4 px-4 md:px-6 text-center">
            <div className="space-y-2">
              <h2
                className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl/none">
                What is a Carbon Footprint?
              </h2>
              <p
                className="mx-auto max-w-3xl text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that
                are generated by our actions. It is a measure of the impact our activities have on the environment and
                climate change.
              </p>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container flex flex-col gap-4 px-4 md:px-6 text-center">
            <div className="space-y-2">
              <h2
                className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl/none">
                Why is it important to reduce our Carbon Footprint?
              </h2>
              <p
                className="mx-auto max-w-3xl text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Reducing our carbon footprint is essential for mitigating climate change and its impacts. By lowering
                the amount of greenhouse gases we produce, we can help slow the rate of global warming, reduce the
                frequency and severity of extreme weather events, and protect the planet for future generations.
              </p>
            </div>
          </div>
        </section>
        <div className="bg-gray-50/90 w-full py-12 md:py-16">
      <div className="container px-4 md:px-6">
        <div className="grid items-center gap-6 lg:grid-cols-[1fr_600px]">
          <div className="space-y-4">
            <div className="space-y-2">
              <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl">Protecting Our Planet</h1>
              <p className="max-w-[600px] text-gray-500 md:text-xl dark:text-gray-400">
                Explore the impact of human actions on our most important ecological places.
              </p>
            </div>
            <Link
              className="inline-flex items-center space-x-2 text-sm font-medium underline transition-transform translate-y-0.5 duration-150 hover:text-gray-950 dark:hover:text-gray-50"
              href="#"
            >
              Explore the Map..
              
            </Link>
          </div>
          <img
            alt="Hero"
            className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
            height="300"
            src={logo}
            width="600"
          />
        </div>
      </div>
    </div>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container flex flex-col gap-4 px-4 md:px-6 text-center">
            <div className="space-y-2">
              <h2
                className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl/none">
                Your Carbon Footprint
              </h2>
              <p
                className="mx-auto max-w-3xl text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Based on your input, your estimated carbon footprint is 12.5 metric tons of CO2 per year.
              </p>
            </div>
            <div className="mx-auto w-full max-w-sm space-y-2">
              <form className="flex flex-col gap-2">
                <label className="sr-only" htmlFor="email">
                  Email
                </label>
                <Input
                  className="peer h-10 border-gray-300 shadow-sm dark:placeholder-gray-400"
                  id="email"
                  placeholder="Enter your email"
                  type="email" />
                <Button type="submit">Sign Up</Button>
                <p className="text-xs text-gray-500 dark:text-gray-400">
                  Sign up to get notified when we launch.
                  <Link className="underline underline-offset-2" href="#">
                    Terms & Conditions
                  </Link>
                </p>
              </form>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 border-t">
          <div className="container flex flex-col gap-4 px-4 md:px-6 text-center">
            <div className="space-y-2">
              <h2
                className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl/none">
                How to Reduce your Carbon Footprint
              </h2>
              <p
                className="mx-auto max-w-3xl text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Here are some tips to help you reduce your carbon footprint:
              </p>
            </div>
            <div className="mx-auto w-full max-w-sm space-y-4">
              <ol className="list-decimal list-inside space-y-2">
                <li>Use public transportation or carpooling</li>
                <li>Switch to energy-efficient appliances and light bulbs</li>
                <li>Reduce, reuse, and recycle</li>
                <li>Conserve water</li>
                <li>Support renewable energy</li>
              </ol>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container flex flex-col gap-4 px-4 md:px-6 text-center">
            <div className="space-y-2">
              <h2
                className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl/none">
                Benefits of Reducing your Carbon Footprint
              </h2>
              <p
                className="mx-auto max-w-3xl text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                By reducing your carbon footprint, you can help protect the environment, improve air quality, and
                conserve natural resources. You can also save money on energy bills and contribute to a more sustainable
                and resilient future.
              </p>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container flex flex-col gap-4 px-4 md:px-6 text-center">
            <div className="space-y-2">
              <h2
                className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl/none">Testimonials</h2>
              <p
                className="mx-auto max-w-3xl text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                "The Carbon Footprint Tracker has made me more aware of my daily activities and their impact on the
                environment. I now make conscious choices to reduce my carbon footprint, such as walking or biking
                instead of driving, using energy-efficient appliances, and recycling. It's easy to use and provides
                practical tips for a greener lifestyle." - Sarah
              </p>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container flex flex-col gap-4 px-4 md:px-6 text-center">
            <div className="space-y-2">
              <h2
                className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl/none">
                Share with your friends
              </h2>
            </div>
            <Button>Share on Twitter</Button>
          </div>
        </section>
      </main>
      </div>
      <footer
        className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Terms of Service
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Privacy
          </Link>
        </nav>
      </footer>
    </div>)
  );
}

export default MainPage;

function MountainIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>)
  );
}
