/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Bihe89QUE0N
 */
import { CardTitle, CardHeader, CardContent, Card } from "../components/ui/card"
import { ResponsiveLine } from "@nivo/line"

export function GraphCarbon() {
  return (
    (<div className="flex flex-col gap-4 w-full items-center">
      <Card className="w-full max-w-3xl">
        <CardHeader className="px-6 pt-6 pb-0">
          <CardTitle className="text-base">Weekly Carbon Emissions</CardTitle>
        </CardHeader>
        <CardContent className="p-0">
          <div className="grid w-full grid-rows-1">
            <div className="flex w-full items-center justify-center p-6">
              <div className="w-full aspect-[2/1] rounded-lg overflow-hidden">
                <LineChart className="w-full aspect-[2/1]" />
              </div>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>)
  );
}


function LineChart(props) {
  return (
    (<div {...props}>
      <ResponsiveLine
        data={[
          {
            id: "Desktop",
            data: [
              { x: "Jan", y: 43 },
              { x: "Feb", y: 137 },
              { x: "Mar", y: 61 },
              { x: "Apr", y: 145 },
              { x: "May", y: 26 },
              { x: "Jun", y: 23 },
            ],
          }
        ]}
        margin={{ top: 10, right: 10, bottom: 40, left: 40 }}
        xScale={{
          type: "point",
        }}
        yScale={{
          type: "linear",
        }}
        axisTop={null}
        axisRight={null}
        axisBottom={null}
        axisLeft={null}
        colors={["#2563eb", "#e11d48"]}
        pointSize={6}
        useMesh={true}
        gridYValues={6}
        theme={{
          grid: {
            line: {
              stroke: "#f3f4f6",
            },
          },
        }}
        role="application" />
    </div>)
  );
}


function LightbulbIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M15 14c.2-1 .7-1.7 1.5-2.5 1-.9 1.5-2.2 1.5-3.5A6 6 0 0 0 6 8c0 1 .2 2.2 1.5 3.5.7.7 1.3 1.5 1.5 2.5" />
      <path d="M9 18h6" />
      <path d="M10 22h4" />
    </svg>)
  );
}
